config/routes.rb
Peregrination::Application.routes.draw do

    resources :trips, only:[:index, :new, :show, :create, :update, :destroy] 
    resources :place 
    resources :relationships, only:[:create, :destroy]
    resources :users
    resources :sessions, only:[:new, :create, :destroy]
    resources :photos
    resources :photoalbums
    resources :ideas

    root 'static_pages#home'
    match '/start',    to: 'static_pages#start',    via: 'get'
    match '/planner',  to: 'static_pages#planner',  via: 'get'
    match '/home', 	   to: 'static_pages#home',	   via: 'get'
    match '/about',    to: 'static_pages#about',    via: 'get'
    match '/form',      to: 'static_pages#form',    via: 'get'
    match "users/:id/prof_pic_upload", to: 'users#prof_pic_upload', :as => :prof_pic_upload, via: 'get'
    match "users/:id/edit_profile", to: "users#edit_profile", :as => :edit_profile, via: "get"
    match "photos/:id/edit_form",  to: "photos#edit_form", :as=>:edit_form, via: "get"
    match "ideas/:id/edit_likes", to: "ideas#edit_likes", :as=>:edit_likes, via: "post"

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	include Geocoder

	def home
		@static = true
		respond_to do |format|
			format.html { render '_home'}
			format.js
		end
	end

	def planner
		@static = true
		# This is necessary because of development environment
		# if request.remote_ip.to_s != "127.0.0.1"
		# 	# temp_city = Geocoder.search( request.remote_ip )[0]
		# 	@city = Geocoder.search("#{request.location.latitude.to_s}, + #{request.location.longitude.to_s}")[0].city
		# else
		# 	@city = Geocoder.search("Seoul")[0].city
		# end
		respond_to do |format|
			format.html { render '_planner'}
			format.js
		end
	end

	def about
	end

	def form
		respond_to do |format|
			format.html { render '_form'}
			format.js
		end
	end

	def start
		@static = true
		respond_to do |format|
			format.html { render '_start'}
			format.js
		end
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_home.html.erb
<div id="exit">
	<div class='container'>
		<div class="col-md-8 col-md-offset-2 jumbotron" style="text-align: center; padding: 0; background-color: transparent">
			<h1 id="header" style="color: white;">SPONTANEOUS FUN.</h1>
		</div>
		<div class="col-md-8 col-md-offset-2" style="text-align: center">
			<h4 style="color: white; margin-bottom: 40px; margin-top: -20px;">Be clueless no more about the adventure that surrounds you</h4>
		</div>
		<div class='col-xs-8 col-md-3 col-sm-3 col-md-offset-2 col-sm-offset-2 col-xs-offset-2' style=" height: 100px;">
			<%= link_to "GENERATE FUN", planner_path, class: 'thumbnail well text-center sharp-corners', id: "generate", style: 'color: black; border: 3px solid black; text-decoration: none; background-color: #89CCC9;'%>
		</div>

		<div class='col-xs-8 col-md-3 col-sm-3 col-md-offset-2 col-sm-offset-2 col-xs-offset-2' style=" height: 100px;">
			<%= link_to "BUILD FUN", start_path, class: 'thumbnail well text-center sharp-corners', id: "build", style: 'color: black; border: 3px solid black; text-decoration: none; background-color: #CC898C;'%>
		</div>
	</div>
</div>

<script type="text/javascript">
	$("#build").hover(function() {
		$("#build").animate({
			"background-color": "#FEBBBE",
			"text-decoration": "none"
		}, 0, function(){});}, function(){
			$("#build").animate({
			"background-color": "#CC898C"
		}, 0, function(){});
		});

	$("#generate").hover(function() {
		$("#generate").animate({
			"background-color": "#BBFEFB",
			"text-decoration": "none"
		}, 0, function(){});}, function(){
			$("#generate").animate({
			"background-color": "#89CCC9"
		}, 0, function(){});
		});
</script>

app/views/static_pages/_planner.html.erb
<style type="text/css">
	.greened {
		background-color: #89CCC9;
		border: none;
	}

	.greened:hover{
		background-color: #BBFEFB;
	}
</style>

<div id="planner_exit">
	<h4 class="container"> <%= link_to("Go Back to Home", root_path, class: "btn btn-default greened")%> </h4>

	<%= form_for(:trips, url: new_trip_path, method: "get") do |f| %>
		<div class='container' style="position: relative; color: white">
			<div class="row" id="error_message">
				<% if flash[:invalid_place]%>
					<p class="text-center alert alert-danger col-md-4 col-sm-4"> <%= flash[:invalid_place] %> </p>
				<% end %>
				<% if flash[:invalid_range]%>
					<p class="text-center alert alert-danger col-md-4 col-sm-4"> <%= flash[:invalid_range] %> </p>
				<% end %>
			</div>
			<div id="base_question" class="form-group">
				<%= f.label :Are_you_a_tourist_or_just_looking_to_lounge?, class: "control-label h2", style: "margin-bottom: 20px; font-family: 'Lato-Light'"%>
				
				<div id="" class="row">
					<div class="col-md-4 col-sm-4">
						<%= f.radio_button :purpose, "tourist", id: "tourism_button", style: "display: none" %>
						<label for="tourism_button" id="tourism" class="col-md-12 col-xs-12 btn btn-default greened" style="margin-bottom: 20px"> Tourist/Trying Something New! </label>
					</div>
				</div>

				<div id="" class="row">
					<div class="col-md-4 col-sm-4">
						<%= f.radio_button :purpose, "hangout", id: "hangout_button", style: "display: none" %>
						<label for="hangout_button" id="hangout" class="col-md-12 col-xs-12 btn btn-default greened"> Just Hangin' Out </label>
					</div>
				</div>
			</div>

			<div id="tourism_2" class="row form-group" style="position: absolute; top: 0; display: none">
				<div class="col-md-10 col-sm-10 col-xs-10">
					<%= f.label :Where_are_you?, class: "control-label h2", style: "margin-bottom: 20px; font-family: 'Lato-Light'" %>
					<div id="location_replace"> 
						<%= f.text_field :location, class: "form-control", id: "select_origin_1",  placeholder: "Location", style: "margin-bottom: 20px"%>
					</div>

					<!-- When the "Use Current Location" box is checked -->
						<% region = request.location.state_code %>
						<% if region.nil? or region.empty? %>
							<% region = request.location.country %>
						<% end %>
						<input class="form-control" style="display: none;margin-bottom: 20px" id="disabledInput" type="text" placeholder="<%=request.location.city%>, <%=region%>" disabled>

						<div id="location" style="font-size: 1.2em"> 
							Use Current Location <%= f.check_box :auto_location %> 
						</div>
					<div id="to_tourism_4" style="margin-top: 20px">
						<%= f.button "Next", type: 'button', class: "form-control btn btn-default greened"%>
					</div>
				</div>

				<div class="col-md-2 col-sm-2 col-xs-2">
					<div id="prev1" class="glyphicon glyphicon-chevron-up btn" style="font-size: 2em">	
					</div>
				</div>
			</div>

			<div id="tourism_4" class="row form-group" style="position: absolute; top: 0; display: none">
				<div class="col-md-10 col-sm-10 col-xs-10">
					<%= f.label :How_far_can_you_afford_to_go?, class: "control-label h2", style: "margin-bottom: 20px;font-family: 'Lato-Light'"%>
					<%= f.text_field :distance, class: "form-control", placeholder: "Miles", style: "margin-bottom: 20px"%> 
					<div id="to_tourism_5">
						<%= f.button "Next", type: 'button', class: "form-control btn btn-default greened"%>
					</div>
				</div>

				<div class="col-md-2 col-sm-2 col-xs-2">
					<div id="prev2" class="glyphicon glyphicon-chevron-up btn" style="font-size: 2em">	
					</div>
				</div>

			</div>

			

			<div id="tourism_5" class="row form_group" style="position: absolute; top: 0; display: none">
				<div class="col-md-10 col-sm-10 col-xs-10">
					<%= f.label "And lastly, how can you get around?", class: "control-label h2", style: "margin-bottom: 20px;font-family: 'Lato-Light'"%> 
					<div style="font-size: 1.2em"> 
						 <%= f.check_box :public_transportation %> Public Transportation
					</div>
					<div style="font-size: 1.2em"> 
						<%= f.check_box :car %> Car/Taxi
					</div>
					<div style="font-size: 1.2em"> 
						 <%= f.check_box :walk %> Pedestrian
					</div>
					<div id="to_tourism_5" style="margin-top: 20px">
						 <%= f.button "Plan it for me!", type: 'submit', class: "form-control btn btn-default greened"%>
					</div>
				</div>

				<div class="col-md-2 col-sm-2 col-xs-2">
					<div id="prev3" class="glyphicon glyphicon-chevron-up btn" style="font-size: 2em">	
					</div>
				</div>

			</div>

		</div>
	<% end %>
</div>

<script type="text/javascript">

	$("#location").click(function(){
		$("#location_replace").toggle();
		$('#disabledInput').toggle();
		// alert("<%= request.location.city %>" + "<%= request.location.state_code %>")
		// $("<p> LOCATION </p>").insertAfter($("#location"));
	});

	$("#tourism").click(function() {
		$("#base_question").hide('slide', { direction: "up", duration: 300});
		$("#error_message").hide('slide', { direction: "up", duration: 300});
		$("#tourism_2").show('slide', {direction: 'down', duration: 300});
	});

	$("#hangout").click(function() {
		$("#base_question").hide('slide', { direction: "up", duration: 300 });
		$("#error_message").hide('slide', { direction: "up", duration: 300});
		$("#tourism_2").show('slide', {direction: 'down', duration: 300});
	});

	$("#to_tourism_4").click(function() {
		$("#tourism_2").hide('slide', { direction: "up", duration: 300 });
		$("#tourism_4").show('slide', {direction: 'down', duration: 300});
	});

	$("#to_tourism_5").click(function() {
		$("#tourism_4").hide('slide', { direction: "up", duration: 300 });
		$("#tourism_5").show('slide', {direction: 'down', duration: 300});
	});

	$("#to_hangout_3").click(function() {
		$("#hangout_2").hide('slide', { direction: "up" , duration: 300});
		$("#hangout_3").show('slide', {direction: 'down', duration: 300});
	});

	$("#to_hangout_4").click(function() {
		$("#hangout_3").hide('slide', { direction: "up" , duration: 300});
		$("#tourism_4").show('slide', {direction: 'down', duration: 300});
	});

	$("#prev1").click(function() {
		$("#tourism_2").hide('slide', { direction: "down", duration: 300});
		$("#base_question").show('slide', { direction: "up", duration: 300});
	});

	$("#prev2").click(function() {
		$("#tourism_4").hide('slide', { direction: "down", duration: 300});
		$("#tourism_2").show('slide', { direction: "up", duration: 300});
	});

	$("#prev3").click(function() {
		$("#tourism_5").hide('slide', { direction: "down", duration: 300});
		$("#tourism_4").show('slide', { direction: "up", duration: 300});
	});

	$("#prev4").click(function() {
		$("#tourism_2").hide('slide', { direction: "down", duration: 300});
		$("#base_question").show('slide', { direction: "up", duration: 300});
	});

	$("#prev5").click(function() {
		$("#hangout_3").hide('slide', { direction: "down", duration: 300});
		$("#hangout_2").show('slide', { direction: "up", duration: 300});
	});

	String.prototype.titleize = function() {
		var words = this.split(' ')
		var array = []
		for (var i=0; i<words.length; ++i) {
			array.push(words[i].charAt(0).toUpperCase() + words[i].toLowerCase().slice(1))
		}
		return array.join(' ')
	}

	$(function() {
		$('#select_origin_1').autocomplete({
			minLength: 2,
			source: '<%= place_index_path(:json) %>',
			focus: function(event, ui) {
				$('#select_origin_1').val(ui.item.name);
				return false;
			},
			select: function(event, ui){
				$('#select_origin_1').val(ui.item.name);
				return false;
			}
		})

		.data( "uiAutocomplete" )._renderItem = function( ul, item ) {
	        return $( "<li></li>" )
	            .data( "item.uiAutocomplete", item )
					// For now which just want to show the person.given_name in the list.
	            .append( "<a>" + item.name.titleize() + "</a>" )
	            .appendTo( ul );
	    };
	});

</script>

app/views/static_pages/_start.html.erb
<style type="text/css">
	.pinked {
		background-color: #CC898C;
		border: none;
	}

	.pinked:hover{
		background-color: #FEBBBE;
	}
</style>

<div id="start_exit">
	<div class="col-md-4 col-md-offset-4" style="color: white; margin-top: 50px">
		
			<%= form_for(:f, url: place_index_path, method: 'get') do |f| %>
				<div class="form-group">


					<%= f.label :search, class: "control-label"%>
					<%= f.text_field :query, class: "form-control", placeholder: "i.e New York, CN Tower, Silicon Valley"%>
				</div>
				<%= f.button "Search", type: "submit", class: "btn btn-default pinked",style: "width: 75px; float: left; margin-right: 20px"%>
				<h4 class="form-group col-md-offset-"> <%= link_to("Go Back", root_path, class: "btn btn-default pinked",style: "width: 75px")%> </h4>

			<% end %>

	</div>
</div>

app/views/static_pages/about.html.erb
<div id="about">
<div class="jumbotron full-width" style="height: 300px; margin-bottom: 0;margin-top: 15px; color: white; background: url('https://forums.oneplus.net/attachments/hongkong-skyline-hd-wallpaper-jpg.546/') no-repeat 40% 45% ; background-size: cover;">
	<h1> Get ready... </h1>
	<h2> To change the way you go places </h2>
	<%= link_to "Click here to get started", root_path, class: "btn btn-primary" %>
</div>

<div class="jumbotron" style="margin-bottom: 0; min-height: 400px; background: url('http://classconnection.s3.amazonaws.com/245/flashcards/1845245/png/great_pyramids1347145134254.png') no-repeat 40% 17% fixed; background-size: cover; clear: both;">
	<div class="col-sm-6 col-md-6 col-md-offset- ">
	    <div class="thumbnail half-opacity text-center">
	    	<h2>Problem with modern day travel:</h2>
	    	<div class="glyphicon glyphicon-plane" style="font-size: 5em"></div>
	    	<h2> People know where to go, don't know what to do once there. People are bored. </h2>
	    </div>
  	</div>
</div>

<div class="jumbotron" style="min-height: 400px; margin-bottom:0 ; background: url('http://www.topvisitplaces.com/wp-content/uploads/2013/12/eiffel-tower-paris-2.jpg') no-repeat 40% 17% fixed; background-size: cover; clear: both;">
	<div class="col-sm-6 col-md-6 col-md-offset-6 ">
	    <div class="thumbnail half-opacity text-center well">
	    	<div class="glyphicon glyphicon-user" style="font-size: 5em"></div>
	    	<h2> There are too many things to do, yet not enough time to do everything </h2>
	    </div>
  	</div>
</div>

<div class="jumbotron" style="height: 600px; margin-bottom: 0; background-color: #fea;">
	<div class="row">
		<div class="col-md-6"> 
			<div class="thumbnail">
				<h2 style="text-align: center"> Our Mission Statement: </h2>
				<p>
					As a company, we seek to build a product that aims to bridge cultural differences in the world by educating and instilling an appreciation for world cultures. We strive to accomplish this by promotion of local culture such as cuisine, art, and custom through a well-designed and beautiful web interface. 
				</p>
				<p>
					An equally important goal we envision is the minimalization of idleness. Whether it is someplace new or in your area of residence, we never want you to be bored or spend too much time thinking of how to not be bored. We want to offer a convenient and quick way to plan things to do, wherever you are. 
				</p>
			</div>
		</div>
		<div class="col-md-6"> 
			<div class="thumbnail">
				<h2 style="text-align: center"> The plan: </h2>
				<p>
					Simply input the kinds of things you want to do, and we'll figure out the rest!
				</p>
			</div>
		</div>
	</div>
</div>

</div>

<script type="text/javascript">
	$(document).ready(function() {
		$("nav").addClass("navbar-fixed-top");
		$("#main-body").replaceWith($("#about"));
		$("#about").css("margin-top", "50px")
	});
</script>

app/views/static_pages/home.js.erb
$('#start_exit').hide("drop", {direction: "right"}, function(){$("#start_exit").html("<%= escape_javascript(render('static_pages/home')) %>");});
// $('#start').css('display', 'none');
$('#start_exit').show("drop", {direction: "left"});
// $("#start").html("<%= escape_javascript(render('static_pages/start')) %>");
$('#planner_exit').hide("drop", {direction: "left"}, function(){$("#planner_exit").html("<%= escape_javascript(render('static_pages/home')) %>");});
// $('#start').css('display', 'none');
$('#planner_exit').show("drop", {direction: "right"});

app/views/static_pages/planner.js.erb
$('#exit').hide("drop", {direction: "right"}, function(){$("#exit").html("<%= escape_javascript(render('static_pages/planner')) %>");});
// $('#start').css('display', 'none');
$('#exit').show("drop", {direction: "left"});
// $("#start").html("<%= escape_javascript(render('static_pages/start')) %>");

app/views/static_pages/start.js.erb
$('#exit').hide("drop", {direction: "left"}, function(){$("#exit").html("<%= escape_javascript(render('static_pages/start')) %>");});
// $('#start').css('display', 'none');
$('#exit').show("drop", {direction: "right"});
// $("#start").html("<%= escape_javascript(render('static_pages/start')) %>");