config/routes.rb
Peregrination::Application.routes.draw do

    resources :trips, only:[:index, :new, :show, :create, :update, :destroy] 
    resources :place 
    resources :relationships, only:[:create, :destroy]
    resources :users
    resources :sessions, only:[:new, :create, :destroy]
    resources :photos
    resources :photoalbums
    resources :ideas

    root 'static_pages#home'
    match '/start',    to: 'static_pages#start',    via: 'get'
    match '/planner',  to: 'static_pages#planner',  via: 'get'
    match '/home', 	   to: 'static_pages#home',	   via: 'get'
    match '/about',    to: 'static_pages#about',    via: 'get'
    match '/form',      to: 'static_pages#form',    via: 'get'
    match "users/:id/prof_pic_upload", to: 'users#prof_pic_upload', :as => :prof_pic_upload, via: 'get'
    match "users/:id/edit_profile", to: "users#edit_profile", :as => :edit_profile, via: "get"
    match "photos/:id/edit_form",  to: "photos#edit_form", :as=>:edit_form, via: "get"
    match "ideas/:id/edit_likes", to: "ideas#edit_likes", :as=>:edit_likes, via: "post"

end

app/models/user.rb
class User < ActiveRecord::Base
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
	before_save {self.email = email.downcase}
	before_save {self.first = first.titleize}
	before_save {self.last = last.titleize}
	has_many :trips, dependent: :destroy
	has_secure_password
	validates :password, length: {minimum: 6}
	validates :blurb, length: {maximum: 140}

	before_create :create_remember_token

	validates :first, presence: true
	validates :last, presence: true

	# User to Photoalbum relationship
  	has_many :user_to_album_relationships, foreign_key: "user_id", dependent: :destroy
  	has_many :albums, through: :user_to_album_relationships, source: :album

  	# User to Idea relationship
  	has_many :user_to_idea_relationships, foreign_key: "user_id", dependent: :destroy
  	has_many :ideas, through: :user_to_idea_relationships, source: :idea

  	# User to Idea likes
  	has_many :user_idea_likes, foreign_key: "user_id", dependent: :destroy

	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def User.hash(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	private
		def create_remember_token
			self.remember_token = User.hash(User.new_remember_token)
		end

		def person_params
		    params.require(:user).permit(:name, :email, :password, :password_confirmation)
	  	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@static = '1'
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			profilepics = Photoalbum.create!(name: "Profile Pictures", default_id: 1)
			ideapics = Photoalbum.create!(name: "Idea Photos", default_id: 1)
			# AlbumToPhotoRelationship.create!(album_id: profilepics.id, photo_id: 1)
			# AlbumToPhotoRelationship.create!(album_id: ideapics.id, photo_id: 1)
			UserToAlbumRelationship.create!(album_id: profilepics.id, user_id: @user.id)
			UserToAlbumRelationship.create!(album_id: ideapics.id, user_id: @user.id)
			
			# Default wanderlust and based_in is Chicago
			@user.update_attribute("wanderlust", 3)
			@user.update_attribute("based_in", 3)

			sign_in @user
			flash[:new] = "Thanks for making an account with us!"
			redirect_to @user
		else
			flash[:error] = "Oops, something went wrong. Please try again"
			@static = '1'
			render 'new'
		end
	end 

	def prof_pic_upload
		@user = User.find(params[:id])
		@album = @user.albums.find_by_name(params[:album])
	    respond_to do |format|
	      format.html {render 'shared/_prof_pic_upload'}
	      format.js 
	    end
  	end

  	def edit_profile
		@user = User.find(params[:id])
	    respond_to do |format|
	      format.html
	      format.js 
	    end
  	end

	def show
		@user = User.find(params[:id])
		@wanderlust = Place.find(@user.wanderlust)
		# Leave as Austin for now
		@current = [41.8819, -87.6278] # This is Austin
		# @current = [request.location.latitude, request.location.longitude]
		# if !@user
		# 	@static = "1"
		# 	render 'sessions/new' and return
		# end
		@feed_items = Idea.city_ideas_aggregate(@wanderlust.id)
	end

	def update
		user = User.find(params[:user][:user_id])
		flash[:update_error] = ""
		if current_user = user

			# If user updated blurb
			if params[:user][:blurb] and !params[:user][:blurb].empty?
				if params[:user][:blurb].length > 140
					flash[:update_error] += "Your blurb can only be a max of 140 characters!"
					redirect_to :back and return
				end
			end

			if params[:user][:based_in] and !params[:user][:based_in].empty?
				new_based_candidates = Place.search(params[:user][:based_in].downcase)
				new_based = 0
				new_based_candidates.each do |c|
					if c.type == "0"
						new_based = c.id
						break
					end
				end
				if !new_based or new_based == 0
					flash[:update_error] += "Oops, your new base does not seem to be a valid city"
					redirect_to :back and return
				end
			end

			if params[:user][:wanderlust] and !params[:user][:wanderlust].empty?
				new_wanderlust_candidates = Place.search(params[:user][:wanderlust].downcase)
				new_wanderlust = 0
				new_wanderlust_candidates.each do |c|
					if c.type == "0"
						new_wanderlust = c.id
						break
					end
				end
				if !new_wanderlust or new_wanderlust == 0
					flash[:update_error] += "Oops, your new wanderlust is not a valid city"
					redirect_to :back and return
				end
			end

			if params[:user][:blurb] and !params[:user][:blurb].empty?
				user.update_attribute("blurb", params[:user][:blurb])
			end
			if params[:user][:based_in] and !params[:user][:based_in].empty?
				user.update_attribute("based_in", new_based)
			end
			if params[:user][:wanderlust] and !params[:user][:wanderlust].empty?
				user.update_attribute("wanderlust", new_wanderlust)
			end
			redirect_to user
		end
	end

	private

	def user_params
		params.require(:user).permit(:first, :last, :email, :password, :password_confirmation, :blurb, :based_in, :wanderlust)
	end
end

app/helpers/users_helper.rb
module UsersHelper
	# Returns the Gravatar (http://gravatar.com/) for the given user.
	def gravatar_for(user)
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url = "https://fbcdn-sphotos-f-a.akamaihd.net/hphotos-ak-xpa1/v/t1.0-9/944641_10151665025540846_1379513979_n.jpg?oh=cd856d70cc5c06092bd8ec7c099d4420&oe=547C95C0&__gda__=1416217371_09c0a46e31293e92d96c3ec496386c41"
		image_tag(gravatar_url, alt: user.email, class: "")
	end
end

app/views/users/edit_profile.js.erb
$("#edit-profile-modal").html("<%= escape_javascript(render partial: 'shared/edit_profile', locals: {user: @user}) %>");

	

app/views/users/new.html.erb
<style type="text/css">
	#submit-button {
		background-color: #CC898C;
		border: none;
	}

	#submit-button:hover{
		background-color: #FEBBBE;
	}
</style>

<div class="container" style="width: 30%; margin-top: -30px; margin-bottom: 30px">

	<% if flash[:error] == "Oops, something went wrong. Please try again" %>
		<p class="alert alert-danger text-center">
			<%= flash[:error] %>
		</p>
	<% end %>
	
	<%= form_for(@user, url: users_path, method: "post") do |f|%>
		<div class="form-group">
			<h2 style="color: white"> <%= f.label :email, class: "control-label" %> </h2>
			<%= f.text_field :email, class: "form-control", placeholder: "Enter valid email address" %>
		</div>

		<div class="form-group">
			<h2 style="color: white"> <%= f.label :name, class: "control-label" %> </h2>
			<div style="display: inline-block">
				<%= f.text_field :first, class: "form-control", placeholder: "First", style: "width: 49%; float: left"%>
				<%= f.text_field :last, class: "form-control", placeholder: "Last", style: "width: 50%; margin-left: 50%;" %>
			</div>
		</div>

		<div class="form-group">
			<h2 style="color: white"> <%= f.label :password, class: "control-label" %> </h2>
			<%= f.password_field :password, class: "form-control", placeholder: "Enter a password" %>
		</div>

		<div class="form-group">
			<h2 style="color: white"> <%= f.label :password_confirmation, class: "control-label" %> </h2>
			<%= f.password_field :password_confirmation, class: "form-control", placeholder: "Confirm Password"%>
		</div>

		<%= f.submit "Create!", id: "submit-button", class: "btn btn-default" %>

	<% end %>
</div>

app/views/users/prof_pic_upload.js.erb
$("#profile-picture-modal").html("<%= escape_javascript(render partial: 'shared/prof_pic_upload', locals: {user: @user, album: @album}) %>");

app/views/users/show.html.erb
<style type="text/css">
	body, html {
		min-width: 1050px;
		background: none;
		color: #313838;
	}

	nav {
	background-color: #D3EDEB;
	border-bottom: 1px solid #DCE8E7;
}

nav a {
	color: #313838;
}

	a{
		color: #399992
	}
	a:hover {
		text-decoration: none;
		color: #1C4A46;
	}
</style>

<% if @user %>
	<% trips = @user.trips %>
<% end %>

<% if flash[:new] == "Thanks for making an account with us!" %>
	</br> <p class="alert alert-success"> <%= flash[:new] %> </p>
<% end %>





<div id="user-main-body">
	<%= render partial: 'shared/profile_cover', locals: {user: @user.id} %>

	<div style="text-align: center">
		<h2> <%= @user.first %>'s: </h2>
	</div>

	<div class="user-row">
		<div>
			<!-- <div style="border: 2px solid white; width: 100%; height: 100%;">
				<% if !trips or trips.empty? %>
					<div class="text-center">
						<h2> You have no wishlists yet :( </h2>
						<h3> <%= link_to "Start adventuring!", root_path%> </h3>
					</div>
				<% else %>
					<%= render partial: 'shared/wishlists', locals: {wishlists: @user.trips} %>
				<% end %> 
			</div> -->
			
			<%= link_to trips_path(:user => @user) do %>
				<h1>Wishlists</h1>
			<% end %>
		</div>

		<div>
			<%= link_to photoalbums_path(:user => @user), method: "get" do %>
				<h1>Photos</h1>
			<% end %>
		</div>

		<div>
			<%= link_to ideas_path(:user => @user) do %>
				<h1>Ideas</h1>
			<% end %>
		</div>
	</div>

	<!-- <div class="user-row-2">
		<div>
			<%= link_to "" do%>
				<h1>Flights</h1>
			<% end %>
		</div>

		<div>
			<%= link_to "" do %>
				<h1>Trails</h1>
			<% end %>
		</div>

		<div>
			<%= link_to "" do %>
				<h1>Roadtrips</h1>
			<% end %>
		</div>
	</div> -->

	<div class="wanderbox" style="display: block; width: 100%; height: 60%; background-color: clear; float: left; margin-bottom: 40px; text-align: center;">
		<h2 style="display: inline; text-align: center; height: 40px;"> <%= @user.first %>'s current wanderlust: 
			<% if @wanderlust %>
				<%= link_to @wanderlust.name.titleize[0..-5], @wanderlust %>
			<%end%>
		</h2>
		<div id="map" style="width: 100%; height: 100%;"></div>
	</div>

	<% if @wanderlust %>
		<div style="text-align: center; clear: both">
			<h2>Get <span style="font-family: 'Lato-Regular'">creative</span> in <%= @wanderlust.name.titleize[0..-5] %></h2>
		</div>
	<% end %>

	<!-- MODALS -->
	<div id="show-idea-modal" class="modal fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>

	<div class="feed-row">
		<% if @feed_items %>
			<% @feed_items.each do |idea| %>
				<% place = Place.find(idea.place_to_idea_relationships.first.place_id) %>
				<% if idea.photos.first %>
					<% bgimage = idea.photos.first.image_url %>
				<% else %>
					<% bgimage = place.image_url %>
				<% end %>
				<div>
					<div class="feed-div-1" style="background: url('<%= asset_path(bgimage) %>'); background-size: cover; opacity: .5">
					</div>
					<div class="feed-div-3" style="font-size: 4em; color: white; -webkit-text-stroke: 1px black;">
						"<%= idea.idea %>"
					</div>
					<div class="feed-div-2">
						<span style="position: absolute; bottom: 10px; left: 20px; font-size: 1.3em"> <%= place.name.titleize %> </span>
					</div>
					<%= link_to "", idea_path(:id=>idea.id, :place_id => place.id), method: "get", class: "feed-link", remote: :true, 'data-toggle'=>"modal", 'data-target'=>'#show-idea-modal' %>
				</div>
			<% end %>
		<% end %>
	</div>

</div>

	


<script type="text/javascript">
	$(function() {
		// $("nav").addClass("navbar-fixed-top");
		
		// $("nav a").css("color", "black");
		// $("a").css("color", "white");
		// $("#main-body").replaceWith($("#about"));
		$("#main-body").css("margin-top", "0px");
		$("#options-links").hide();
		$("#options-links-wanderboard").text("wanderboard");
	});

	$(function() {
		$(".feed-row a").hover(function() {
			$(this).parent().find(".feed-div-2").show('fade', 120);
		}, function(){
			$(this).parent().find(".feed-div-2").hide('fade', 120);
		})
	})

	$(function() {
		$(".user-row a").hover(function() {
			$(this).animate({
				"opacity": "0.7"
			}, 150);
		}, function(){
			$(this).animate({
				"opacity": "1.0"
			}, 150);
		});
	});

	$(function() {
		$(".user-row-2 a").hover(function() {
			$(this).animate({
				"opacity": "0.7"
			}, 150);
		}, function(){
			$(this).animate({
				"opacity": "1.0"
			}, 150);
		});
	});

	$(".transport-label").mouseenter(function (){
		$(this).css("background-color", "#B3E7E8");
	});
	$(".transport-label").mouseleave(function (){
		$(this).css("background-color", "rgba(255,255,255,0.6)");
	});

	
	<% if @user.wanderlust %>
		$(function(){
			handler = Gmaps.build('Google');
			handler.buildMap({ provider: {zoom: 12}, internal: {id: 'map' }}, function() {
				displayOnMap();
			});
		});

		function displayOnMap() {
			var marker = {
		    	lat: '<%= Place.find(@user.wanderlust).coords["c1"][0] %>',
		    	lng: '<%= Place.find(@user.wanderlust).coords["c1"][1] %>'
		  	};
			var marker_c = handler.addMarker(marker);
			marker_c.getServiceObject().setIcon("http://icons.iconarchive.com/icons/icons-land/vista-map-markers/48/Map-Marker-Ball-Azure-icon.png");
		  	handler.map.centerOn(marker_c);
		}
	<% end %>
</script>