config/routes.rb
Peregrination::Application.routes.draw do

    resources :trips, only:[:index, :new, :show, :create, :update, :destroy] 
    resources :place 
    resources :relationships, only:[:create, :destroy]
    resources :users
    resources :sessions, only:[:new, :create, :destroy]
    resources :photos
    resources :photoalbums
    resources :ideas

    root 'static_pages#home'
    match '/start',    to: 'static_pages#start',    via: 'get'
    match '/planner',  to: 'static_pages#planner',  via: 'get'
    match '/home', 	   to: 'static_pages#home',	   via: 'get'
    match '/about',    to: 'static_pages#about',    via: 'get'
    match '/form',      to: 'static_pages#form',    via: 'get'
    match "users/:id/prof_pic_upload", to: 'users#prof_pic_upload', :as => :prof_pic_upload, via: 'get'
    match "users/:id/edit_profile", to: "users#edit_profile", :as => :edit_profile, via: "get"
    match "photos/:id/edit_form",  to: "photos#edit_form", :as=>:edit_form, via: "get"
    match "ideas/:id/edit_likes", to: "ideas#edit_likes", :as=>:edit_likes, via: "post"

end

app/views/shared/_current_itinerary.html.erb
<div class="well container col-md-6 float-right">
	<h4 class="text-center">Current Itinerary</h4>
	<% if flash[:error] == "Oops, you forgot to name your trip!"%>
		<p class="text-center alert alert-danger"> <%= flash[:error] %> </p>
	<% end %>
	<% if flash[:error] == "Your trip appears to be empty"%>
		<p class="text-center alert alert-danger"> <%= flash[:error] %> </p>
	<% end %>
	<% if @temptrip != nil %>
		<% @temptrip.each do |place|%>
			<div class="well half-opacity">
			<%= link_to place.titleize, p = Place.find_by_name(place)%>
			<span class="float-right"><%= link_to "Remove", place_index_path(:tripid => @tripid, :id => p.id, :search => @search, :store => @temptrip-[place], :request => "remove"), method: "get" %> </span>
			</div>
		<% end %>
	<% end %>
		<div class="form-horizontal"> 
			<% if @tripid == nil %>
			<!-- Form for a completely new trip -->
				<%= form_for(:trips, url: trips_path, method: "post") do |f| %> 
					<div class="form-group">
							<div class="col-md-8">
							<%= f.text_field :name, class: "form-control", placeholder: "Enter name for trip" %>
							</div>

						<% if @temptrip != nil %>
							<% @temptrip.each do |place| %>
								<%= f.hidden_field :store, :multiple => true, :value => place %>
							<% end %>
						<% end %>
					
						<div class="col-md-4">
							<%= f.submit "Save Trip!", class: "btn btn-primary col-md-12"%>
						</div>
					</div>
				<% end %>

			<% else %>
			<!-- Form for a trip being edited -->
				<%= form_for(Trip.find(@tripid), url: trip_path(@tripid), method: "patch") do |f|%>
					<div class="form-group">
						<div class="col-md-8">
							<%= f.label "Trip name: " + Trip.find(@tripid).name %>
						</div>

						<% if @temptrip != nil %>
							<% @temptrip.each do |place| %>
								<%= f.hidden_field :store, :multiple => true, :value => place %>
							<% end %>
						<% else %>
							<%= f.hidden_field :store, :value => nil %>
						<% end %>
				
						<div class="col-md-4">
							<%= f.submit "Save Trip!", class: "btn btn-primary col-md-12"%>
						</div>
					</div>
				<% end %>
			<% end %>
		</div>
</div>

app/views/shared/_edit_profile.html.erb
<div class="modal-dialog">
    <div class="modal-content">

        <div class="modal-body">
            <p> Edit Your Profile </p>
            
            <%= form_for(:user, url: user_path, method: "patch") do |f| %>

                <div class="form-group">
                    <h3> <%= f.label "Home base: ", class: "control-label", style: "float: left; width: 49%" %> </h3>
                    <%= f.text_field :based_in, value: "", class: "form-control", placeholder: "Currently based out of", style: "width: 50%; margin-left: 50%" %>
                </div>
                <div class="form-group">
                    <h3> <%= f.label "Current Wanderlust: ", class: "control-label", style: "float: left; width: 49%" %> </h3>
                    <%= f.text_field :wanderlust, value: "", placeholder: "Where would you rather be?", class: "form-control", style: "width: 50%; margin-left: 50%" %>
                </div>
                <div class="form-group">
                    <h3> <%= f.label "Blurb: ", class: "control-label", style: "float: left; width: 49%" %> </h3>
                    <%= f.text_field :blurb, value: "", placeholder: "Describe yourself in 140 characters", class: "form-control", style: "width: 50%; margin-left: 50%" %>
                </div>
                <%= f.hidden_field :user_id, value: user.id %>
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                
                <%= f.submit "Save", id: "submit", class: "btn btn-default", style: "background-color: #ABEDEA" %>
            <% end %>
           
        </div>
    </div>
</div>

<script type="text/javascript">
    $("#submit").hover(function(){
        $(this).css("background-color", "#CDFAF8");
    }, function(){
        $(this).css("background-color", "#ABEDEA");
    });

</script>

app/views/shared/_prof_pic_upload.html.erb
<div class="modal-dialog">
    <div class="modal-content">

        <div class="modal-body">
            <p> Edit Profile Picture for <%= user.first %></p>
            <p> <%= image_tag album.default.image_url(:thumb) %> </p>
            <%= form_for(:photos, url: photos_path, method: "post", :html => {:multipart => true}) do |f| %>
                <p>
                    <%= f.file_field :image, id: "file-button", style: "display: none"%>
                    <%= f.hidden_field :album, value: album.id %>
                    <%= f.hidden_field :case, value: "profile-picture" %>
                    <%= f.hidden_field :user_id, value: user.id %>
                    <label for="file-button" class="btn btn-default"> Choose New Picture </label>
                </p>
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                
                <%= f.submit "Save", id: "submit", class: "btn btn-default", style: "background-color: #ABEDEA" %>
            <% end %>
           
        </div>
    </div>
</div>

<script type="text/javascript">
    $("#submit").hover(function(){
        $(this).css("background-color", "#CDFAF8");
    }, function(){
        $(this).css("background-color", "#ABEDEA");
    })
</script>

app/views/shared/_profile_cover.html.erb
<style type="text/css">
	body, html {
		min-width: 1000px;
		background: none;
	}
	#index-options {
		text-align: center;
		font-size: 1.5em;
		font-family: "Lato-Light";
		min-height: 50px;
		background-color: rgba(223,235,234,1);
		width: 100%;
	}
	nav {
		background-color: #D3EDEB;
		border-bottom: 1px solid #DCE8E7;
	}

	nav a {
		color: #313838;
	}

	#index-options a {
		font-family: "Lato-Light";
	}

	.glyphicon-camera {
		font-size: 30pt;
		position: absolute;
		top: 50%;
		color: white;
		left: 50%;
		margin-top: -15pt;
		margin-left: -15pt;
		display: none;
	}

	.glyphicon-camera:hover {
		text-decoration: none;
		color: black;
	}
	<% if @user.based_in %>
		#profile-cover-tag {
			display: block;
			background: url("<%= asset_path(Place.find(@user.based_in).image_url) %>") no-repeat center;
			background-size: 100%;
			width: 100%;
			height: 290px;
			margin-bottom: -290px;
			opacity: .3;
			background-color: white;
		}
	<% end %>
</style>

<div id="profile-cover-tag"></div>
<div class="wanderbox" style="width: 90%; height: 290px; margin: 0 auto; background-color: clear; position: relative; text-align: center">
<div class="profile-image-container">
	<% if @user == current_user %>
<!-- 					<a id="profile-pic-upload" class="glyphicon glyphicon-camera"></a>
-->					<%= link_to "", prof_pic_upload_path(:id => @user.id, :album => "Profile Pictures"), {remote: :true, 'data-toggle' =>  "modal", 'data-target' => '#profile-picture-modal', class: "glyphicon glyphicon-camera"}  %>
		
	<% end %>
	<!-- This is the profile picture -->
	<% album = @user.albums.first %>
	<% if album.photos.empty? %>
		<%= image_tag asset_path("default.png"), id: "profile-image-tag" %>
	<% else %>
		<%= link_to photo_path(:id => 0, :album => @user.albums.first.id, user: @user.id), {remote: :true, 'data-toggle' =>  "modal", 'data-target' => '#show-image-modal', :class=> "image-show"} do %>
			<%= image_tag @user.albums.first.default.image_url(), id: "profile-image-tag" if @user.albums.first.default_id? %>
		<% end %>
	<% end %>
</div>

<!-- MODALS -->
<div id="profile-picture-modal" class="modal fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>
<div id="edit-profile-modal" class="modal fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>
<div id="show-image-modal" class="modal fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>

<!-- <div class="wander-methods">
	<div> <p class="transport-label"> Flights </p> </div>
	<div> <p class="transport-label"> Roads </p> </div>
	<div> <p class="transport-label"> Trails </p> </div>
	<div> <p class="transport-label"> Rails </p> </div>
</div> -->
<div id="profile-info" style="background-color: clear; height: 100%; margin-left: 250px; text-align: right;">
	
	<h2 style="margin-bottom: 0px"> 
		<%= link_to edit_profile_path(:id => @user.id), {remote: :true, 'data-toggle' =>  "modal", 'data-target' => '#edit-profile-modal', id: "edit-link", style: "font-size: 15pt; display: none;"} do %>
		Edit Info
	<% end %>&nbsp&nbsp&nbsp
	<%= link_to user_path(@user.id) do %>
		<%= @user.first %> <%= @user.last %>  
	<% end %> </h2>
	<h2>Based in: 
		<% if @user.based_in %>
			<%= link_to Place.find(@user.based_in), style: "display: inline-block, margin-bottom: -10px" do %>
			<%= Place.find(@user.based_in).name[0..-5].titleize %>
		<% end %>
	<% end %> </h2>

	<h2> Current wanderlust: 
		<% if @user.wanderlust %>
			<%= link_to Place.find(@user.wanderlust), style: "display: inline-block" do %>
			<%= Place.find(@user.wanderlust).name[0..-5].titleize %>
		<% end %>
	<% end %> </h2>
	<p> <h2 style="display: inline"> Blurb:</h2> <%= @user.blurb %> </p>
</div>

</div>
<div id="index-options">
	<%= @user.first %> <%= @user.last %>'s <%= link_to "wanderboard:", user_path(@user.id), id: "options-links-wanderboard", style: "font-family: Lato-Regular" %>
	<div id="options-links">
		<%= link_to "Wishlists", trips_path(:user => @user) %>&nbsp-
		<%= link_to "Photos", photoalbums_path(:user => @user) %>&nbsp-
		<%= link_to "Ideas", ideas_path(:user => @user) %> <!--&nbsp-
		 <%= link_to "Flights" %>&nbsp-
		<%= link_to "Trails" %>&nbsp-
		<%= link_to "Roadtrips" %> -->
	</div>
</div>

<script type="text/javascript">
$(function(){
	$("#profile-info").hover(function() {
		if ("<%= @user == current_user %>" === "true"){
			$("#edit-link").show();
		}
	}, function() {
		$("#edit-link").hide();
	});
	// $("#profile-image-tag").colorbox({href: document.getElementById("profile-image-tag").src});
	if ("<%= flash[:update_error] %>" != ""){
		alert("<%= flash[:update_error] %>");
	}
})
	$(function() {
		if ("<%= @user == current_user %>" === "true"){
			$(".profile-image-container").mouseenter(function() {
				$(".glyphicon-camera").show('fade', 200);
				$(".profile-image-container").animate({
					"opacity": "0.7"
				}, 200)
			});
			$(".profile-image-container").mouseleave(function() {
				$(".glyphicon-camera").hide('fade', 200);
				$(".profile-image-container").animate({
					"opacity": "1.0"
				}, 200)
			});
		}
	})
</script>

app/views/shared/_search.html.erb
<div class="form-inline">
<div  style="width: 40%; position: absolute; top: 50%; margin-top: -27px; margin-left: 10px;">
<%= form_for(:f, url: place_index_path, method: 'get') do |f| %>


			<div class="form-group" style="float: left; width: 70%; ">
				<%= f.text_field :query, style: "display: inline-block", class: "form-control", placeholder: "Search again" %>
			</div>
			<% if temptrip != nil %>
				<% temptrip.each do |place| %>
					<%= f.hidden_field :store, :multiple => true, :value => place %>
				<% end %>
			<% end %>
			<% if tripid != nil %>
				<%= f.hidden_field :tripid, :value => tripid %>
			<% end %>
			<%= f.hidden_field :searchtype, value: "re" %>

			<div style="float: left; width: 20%; margin-right: 9%;">
				<%= f.button "Search", type: 'submit', class: "btn btn-default"%>
			</div>

<% end %>

</div>
</div>

app/views/shared/_wishlists.html.erb
<style type="text/css">
	.wishlist-container {
		height: 50px;
		line-height: 50px;
		width: 100%;
		background-color: white;
	}

	.wishlist-container a {
		font-family: "Lato-Light";
		font-size: 1.7em;
		margin-left: 10px;
		text-decoration: none;
		color: black;
	}

	.wishlist-container a:hover {
		color: white;
	}
</style>

<h3 class="text-center" style="margin-top: 10px;">Your currently saved wishlists:</h3>

<% wishlists.each do |wishlist| %>
	<div class="wishlist-container">
		<span style="margin-left: 10px; margin-bottom: 20px; font-size: 0.9em">&#9654;</span><%= link_to wishlist.name, wishlist %>
		<p style="display: inline; font-size: 0.6em"> <%= link_to "-edit-" %> </p>
		<p style="display: inline; font-size: 0.6em"> <%= link_to "-delete-"%> </p>
	</div>
<% end %>

<script type="text/javascript">
	$(".wishlist-container").mouseenter(function() {
		$(this).animate({"background-color": "#EBD3ED"}, 0, function() {});
	});
	$(".wishlist-container").mouseleave(function() {
		$(this).animate({"background-color": "#FFF"}, 0);
	});

</script>