config/routes.rb
Peregrination::Application.routes.draw do

    resources :trips, only:[:index, :new, :show, :create, :update, :destroy] 
    resources :place 
    resources :relationships, only:[:create, :destroy]
    resources :users
    resources :sessions, only:[:new, :create, :destroy]
    resources :photos
    resources :photoalbums
    resources :ideas

    root 'static_pages#home'
    match '/start',    to: 'static_pages#start',    via: 'get'
    match '/planner',  to: 'static_pages#planner',  via: 'get'
    match '/home', 	   to: 'static_pages#home',	   via: 'get'
    match '/about',    to: 'static_pages#about',    via: 'get'
    match '/form',      to: 'static_pages#form',    via: 'get'
    match "users/:id/prof_pic_upload", to: 'users#prof_pic_upload', :as => :prof_pic_upload, via: 'get'
    match "users/:id/edit_profile", to: "users#edit_profile", :as => :edit_profile, via: "get"
    match "photos/:id/edit_form",  to: "photos#edit_form", :as=>:edit_form, via: "get"
    match "ideas/:id/edit_likes", to: "ideas#edit_likes", :as=>:edit_likes, via: "post"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<%= favicon_link_tag asset_path('temp_favi.ico') %>
	<title><%= full_title(yield(:title)) %></title>
	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	<%= stylesheet_link_tag "jquery-ui.min.css" %>
	<%= stylesheet_link_tag "colorbox-master/example1/colorbox.css" %>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<%= javascript_include_tag 'jquery.min', 'jquery-ui.min.js' %>
	<%= javascript_include_tag "colorbox-master/jquery.colorbox-min.js" %>
	<%= csrf_meta_tags %>
	<!-- <meta name="viewport" content="width=device-width, initial-scale=1.0"> -->
</head>
<body>
	<!-- Goodness i am a CSS noob -->
	<nav class="navbar sharp-corners" role="navigation" style="margin-bottom: -0px; border-top: none; border-left: none; border-right: none; border-bottom: none; ">
        <div class="container">
                
                 <%= link_to "wanderhub", root_path, class: "navbar-brand", style: "font-size: 20pt; ; font-family: 'Lato-Light'"%>


            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="navbar-right" id="navbar-ex1-collapse">
      			<div class=" navbar-form navbar-left">
	      			<%= form_for(:form, url: place_path(id: 1), method: "get") do |f| %>
	      				<div class="form-group" style="">
	      					<%= f.text_field :query, id: "select_origin", class: "form-control", placeholder: "Look up a place"+"\u0020\u0020\u2315" %>
	      				</div>
      					<!-- <%= f.button "Search", type: 'submit', class: "btn btn-default"%> -->
	      			<% end %>
      			</div>
                <ul class="nav navbar-nav navbar-right" style="">
                    	<li> <%= link_to "Home", root_path, style: ""%> </li>
						<li> <%= link_to "About", about_path, style: ""%> </li>

						<% if current_user == nil %>
							<li> <%= link_to "Sign In", new_session_path, method: "get", style: ""%> </li>
							<li> <%= link_to "Sign Up", new_user_path, style: ""%> </li>
						<% end %>

						<% if current_user != nil %>
							<li> <%= link_to "wanderboard", user_path(current_user.id), method: "get", style: ""%> </li>
						<% end %>

						<% if current_user != nil %>
							<li> <%= link_to "Sign off", session_path(current_user.id), method: "delete", style: ""%> </li>
						<% end %>
                </ul>
                
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
    <% if @static %>
		<div id="main-body"style="min-height: 500px;">
			<div class="home-band container" style="margin-top: 50px;">
				<%= yield %>
			</div>

			<div style="margin-top: 100px;">
				<h3><%= link_to "What is wanderhub?", about_path, style: "color: white; text-align: center", class: "col-md-6 col-sm-6 col-xs-8 col-md-offset-3 col-sm-offset-3 col-xs-offset-2"%></h3>
			</div>
		</div>
	<% else %>
		<div id="main-body" class=" full-width transparent" style="min-height: 500px;">
		<%= yield %>
	</div>
	<% end %>
	<!-- <%= debug(params) if Rails.env.development? %> -->

</body>

<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>


<script type="text/javascript">
	$(function() {
		// $("nav").addClass("navbar-fixed-top");
		// $("#main-body").replaceWith($("#about"));
		$("#main-body").css("margin-top", "0px")
	});

	String.prototype.titleize = function() {
		  var words = this.split(' ')
		  var array = []
		  for (var i=0; i<words.length; ++i) {
		    	array.push(words[i].charAt(0).toUpperCase() + words[i].toLowerCase().slice(1))
		  }
		  return array.join(' ')
	}

	$(function() {
		$('#select_origin').autocomplete({
			minLength: 3,
			source: '<%= place_path(:json) %>',
			focus: function(event, ui) {
				$('#select_origin').val(ui.item.name.titleize());
				return false;
			},
			select: function(event, ui){
				$('#select_origin').val(ui.item.name.titleize());
				return false;
			}
		})

		.data( "uiAutocomplete" )._renderItem = function( ul, item ) {
	        return $( "<li></li>" )
	            .data( "item.uiAutocomplete", item )
					// For now which just want to show the person.given_name in the list.
	            .append( "<a>" + item.name.titleize() + "</a>" )
	            .appendTo( ul );
	    };
	});
</script>
</html>